### ISSUE TITLE
Apparently redundant parent App class

### ISSUE THREAD

**Issue by takluyver** [jupyter/jupyter_qtconsole#3]
@minrk, in 129c5af467c46fe29cd6c489278f719d83683d55, you made the application class look like this:

```python
class JupyterQtConsoleApp(object):
    pass

class JupyterQtConsoleApp(JupyterApp, JupyterConsoleApp, JupyterQtConsoleApp):
    ...
```

Is there a good reason for this pattern, or is it a leftover from some debugging? If there's a reason, let's add a comment explaining it.

**Comment by minrk** [comment]
I think it's leftover from figuring out the move from IPythonConsoleApp to JupyterConsoleApp, and not I don't think it's necessary. Removed in #4.

**Comment by minrk** [comment]
I just remembered why this was here - it should be IPythonQtConsole as a deprecation name. It must have been caught by a find-replace.
